# Generated by Django 2.1.7 on 2019-02-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparat',
            name='model',
            field=models.CharField(choices=[('RES_IBREEZE_AUTO_CPAP', 'Resvent iBreeze Auto CPAP'), ('LOEWENSTEIN_PRISMA_AUTO_CPAP', 'Loewenstein Prisma Auto CPAP')], default='RES_IBREEZE_AUTO_CPAP', max_length=128),
        ),
    ]
